name: PR hygiene

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Require a type label
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "feat, enhance, fix, internal"
      - name: Require a user-facing flag
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "user-facing: yes, user-facing: no"
